language: node_js
node_js:
  - 14

services:
  - docker

# Pre-testing installs
install:
  - echo "Nothing needs to be installed"

# Scripts to be run such as tests
install:
  - echo "Nothing needs to be installed"

before_script:
  - echo "No tests. Yes there will be tests"

script:
  - docker --version
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  # Tagging
  - docker tag udagram-api-feed kantee92/udagram-api-feed:v2a
  - docker tag udagram-api-user kantee92/udagram-api-user:v2a
  - docker tag udagram-frontend kantee92/udagram-frontend:v2a
  - docker tag udagram-reverseproxy kantee92/udagram-reverseproxy:v2a

# Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push kantee92/udagram-api-feed:v2a
  - docker push kantee92/udagram-api-user:v2a
  - docker push kantee92/udagram-frontend:v2a
  - docker push kantee92/udagram-reverseproxy:v2a