version: "3"
services:
  reverseproxy:
    build:
      context: ./udagram-reverseproxy
    image: udagram-reverseproxy:v2a
  backend_user:
    build:
      context: ./udagram-api-user
    image: udagram-api-user:v2a
  backend_feed:
    build:
      context: ./udagram-api-feed
    image: udagram-api-feed:v2a
  frontend:
    build:
      context: ./udagram-frontend
    image: udagram-frontend:local