apiVersion: v1
kind: Service
metadata:
  labels:
    service: frontend
  name: frontend
spec:
  ports:
    - name: "8100"
      port: 8100
      targetPort: 80
      protocol: TCP
  selector:
    service: frontend
  type: LoadBalancer
